source: docs/holdings_fund_list.md
synced_at: '2026-05-29T03:57:47.948590+00:00'
funds:
- srtn_cd: ''
  alias: F01_한국투자미국배당귀족증권자H_주식_C_e
  fnd_nm: 한국투자미국배당귀족증권자H(주식)C-e
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F02_한국밸류글로벌배당인컴증권자_주식_C_E
  fnd_nm: 한국밸류글로벌배당인컴증권자(주식)C-E
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F03_미래에셋글로벌헬스케어증권자1_주식_C_e
  fnd_nm: 미래에셋글로벌헬스케어증권자1(주식)C-e
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F04_NH_Amundi_러_브증권자_주식_Ce
  fnd_nm: NH-Amundi 러-브증권자[주식]Ce
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F05_신한코리아롱숏증권자_주식_A_e
  fnd_nm: 신한코리아롱숏증권자[주식]A-e
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F06_유리글로벌거래소증권자1호_주식_C_e
  fnd_nm: 유리글로벌거래소증권자1호[주식]C-e
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F07_우리미국단기채공모주증권자1호_H_A_e
  fnd_nm: 우리미국단기채공모주증권자1호(H)A-e
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F08_신한삼성전자알파증권자1호_채권혼합_C_e
  fnd_nm: 신한삼성전자알파증권자1호[채권혼합]C-e
  fnd_tp: 혼합
  enabled: false
- srtn_cd: ''
  alias: F09_한국투자크레딧포커스ESG증권자1_채권_C_e
  fnd_nm: 한국투자크레딧포커스ESG증권자1(채권)C-e
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F10_한화단기하이일드증권자_채권_C_E
  fnd_nm: 한화단기하이일드증권자(채권)C-E
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F11_미래에셋인도채권증권자1호_채권_C_e
  fnd_nm: 미래에셋인도채권증권자1호(채권)C-e
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F12_미래에셋글로벌다이나믹증권1호_채권_C_e
  fnd_nm: 미래에셋글로벌다이나믹증권1호(채권)C-e
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F13_미래에셋미국달러우량회사채1_H_채권Ce
  fnd_nm: 미래에셋미국달러우량회사채1(H)채권Ce
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F14_NH_국채10년인덱스자_채권Ce
  fnd_nm: NH 국채10년인덱스자-채권Ce
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F15_삼성ABF코리아장기채권인덱스증권_채권_Re
  fnd_nm: 삼성ABF코리아장기채권인덱스증권[채권]Re
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F16_유진챔피언중단기채증권자투자_채권_Ce
  fnd_nm: 유진챔피언중단기채증권자투자(채권)Ce
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F17_미래에셋브라질하이인컴채권자_채권_Ce
  fnd_nm: 미래에셋브라질하이인컴채권자[채권]Ce
  fnd_tp: 채권
  enabled: false
- srtn_cd: K55301D51271
  alias: TDF2050_Ce
  fnd_nm: 미래에셋전략배분적격TDF2050혼합자C-e
  fnd_tp: 혼합(TDF)
  enabled: true
- srtn_cd: ''
  alias: F19_미래에셋로저스Commodity인덱스특별자C
  fnd_nm: 미래에셋로저스Commodity인덱스특별자C-e
  fnd_tp: 기타/원자재
  enabled: false
- srtn_cd: ''
  alias: F20_카디안미국투자적격회사채자_H_C_E
  fnd_nm: 카디안미국투자적격회사채자[H]C-E
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F21_하나글로벌리츠부동산자_재간접형_C_E
  fnd_nm: 하나글로벌리츠부동산자[재간접형]C-E
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F22_피델리티아시아하이일드증권_채권재간접_Ce
  fnd_nm: 피델리티아시아하이일드증권(채권재간접)Ce
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F23_피델리티글로벌배당인컴증권자주식재간접Ce
  fnd_nm: 피델리티글로벌배당인컴증권자주식재간접Ce
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F24_한국투자미국장기국채증권자H_재간접형_C_e
  fnd_nm: 한국투자미국장기국채증권자H(재간접형)C-e
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F25_다올JP모건글로벌투자적격등급회사채H_Ce
  fnd_nm: 다올JP모건글로벌투자적격등급회사채H_Ce
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F26_한화글로벌매크로증권자_주혼재간접CE
  fnd_nm: 한화글로벌매크로증권자-주혼재간접CE
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F27_미래에셋N2글로벌자산배분30증권1호C_e
  fnd_nm: 미래에셋N2글로벌자산배분30증권1호C-e
  fnd_tp: 혼합
  enabled: false
- srtn_cd: ''
  alias: F28_NH_Amundi_JP모간글로벌배당증권자_H
  fnd_nm: NH-Amundi JP모간글로벌배당증권자(H)Ae
  fnd_tp: 주식
  enabled: false
- srtn_cd: ''
  alias: F29_삼성OCIO솔루션안정형증권_혼합재간접_Ae
  fnd_nm: 삼성OCIO솔루션안정형증권[혼합재간접]Ae
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F30_삼성누버거버먼이머징국공채플러스자H_Ce
  fnd_nm: 삼성누버거버먼이머징국공채플러스자H_Ce
  fnd_tp: 채권
  enabled: false
- srtn_cd: ''
  alias: F31_유경플레인바닐라글로벌리츠부동산자Ce
  fnd_nm: 유경플레인바닐라글로벌리츠부동산자Ce
  fnd_tp: 부동산/리츠
  enabled: false
- srtn_cd: ''
  alias: F32_삼성누버거버먼미국리츠H_REITs재간접_Ce
  fnd_nm: 삼성누버거버먼미국리츠H[REITs재간접]Ce
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F33_한화K리츠플러스부동산자H_리츠재간접C_e
  fnd_nm: 한화K리츠플러스부동산자H-리츠재간접C-e
  fnd_tp: 재간접
  enabled: false
- srtn_cd: ''
  alias: F34_카디안미국뱅크론특별자산자_H_C_E
  fnd_nm: 카디안미국뱅크론특별자산자(H)C-E
  fnd_tp: 채권/특별자산
  enabled: false
